/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CredentialAnchor {
      
    export type RootRecordStruct = {issuer: AddressLike, anchoredAt: BigNumberish, revokedAt: BigNumberish, revoked: boolean, batchIdHash: BytesLike}

    export type RootRecordStructOutput = [issuer: string, anchoredAt: bigint, revokedAt: bigint, revoked: boolean, batchIdHash: string] & {issuer: string, anchoredAt: bigint, revokedAt: bigint, revoked: boolean, batchIdHash: string }
  
    }

  export interface CredentialAnchorInterface extends Interface {
    getFunction(nameOrSignature: "anchorRoot" | "getBatchRoot" | "getRootRecord" | "isAuthorizedIssuer" | "isRootActive" | "isRootAnchored" | "owner" | "revokeRoot" | "setIssuerAuthorization" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "IssuerAuthorizationUpdated" | "OwnershipTransferred" | "RootAnchored" | "RootRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorRoot', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'getBatchRoot', values: [string]): string;
encodeFunctionData(functionFragment: 'getRootRecord', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isAuthorizedIssuer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRootActive', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isRootAnchored', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setIssuerAuthorization', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'anchorRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRootRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuthorizedIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRootActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRootAnchored', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setIssuerAuthorization', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace IssuerAuthorizationUpdatedEvent {
      export type InputTuple = [issuer: AddressLike, authorized: boolean];
      export type OutputTuple = [issuer: string, authorized: boolean];
      export interface OutputObject {issuer: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RootAnchoredEvent {
      export type InputTuple = [root: BytesLike, batchIdHash: BytesLike, issuer: AddressLike, batchId: string, anchoredAt: BigNumberish];
      export type OutputTuple = [root: string, batchIdHash: string, issuer: string, batchId: string, anchoredAt: bigint];
      export interface OutputObject {root: string, batchIdHash: string, issuer: string, batchId: string, anchoredAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RootRevokedEvent {
      export type InputTuple = [root: BytesLike, batchIdHash: BytesLike, issuer: AddressLike, revokedBy: AddressLike, revokedAt: BigNumberish];
      export type OutputTuple = [root: string, batchIdHash: string, issuer: string, revokedBy: string, revokedAt: bigint];
      export interface OutputObject {root: string, batchIdHash: string, issuer: string, revokedBy: string, revokedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CredentialAnchor extends BaseContract {
    
    connect(runner?: ContractRunner | null): CredentialAnchor;
    waitForDeployment(): Promise<this>;

    interface: CredentialAnchorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorRoot: TypedContractMethod<
      [root: BytesLike, batchId: string, ],
      [void],
      'nonpayable'
    >
    

    
    getBatchRoot: TypedContractMethod<
      [batchId: string, ],
      [string],
      'view'
    >
    

    
    getRootRecord: TypedContractMethod<
      [root: BytesLike, ],
      [CredentialAnchor.RootRecordStructOutput],
      'view'
    >
    

    
    isAuthorizedIssuer: TypedContractMethod<
      [issuer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRootActive: TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isRootAnchored: TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokeRoot: TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setIssuerAuthorization: TypedContractMethod<
      [issuer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorRoot'): TypedContractMethod<
      [root: BytesLike, batchId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBatchRoot'): TypedContractMethod<
      [batchId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRootRecord'): TypedContractMethod<
      [root: BytesLike, ],
      [CredentialAnchor.RootRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isAuthorizedIssuer'): TypedContractMethod<
      [issuer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRootActive'): TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRootAnchored'): TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRoot'): TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setIssuerAuthorization'): TypedContractMethod<
      [issuer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'IssuerAuthorizationUpdated'): TypedContractEvent<IssuerAuthorizationUpdatedEvent.InputTuple, IssuerAuthorizationUpdatedEvent.OutputTuple, IssuerAuthorizationUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RootAnchored'): TypedContractEvent<RootAnchoredEvent.InputTuple, RootAnchoredEvent.OutputTuple, RootAnchoredEvent.OutputObject>;
getEvent(key: 'RootRevoked'): TypedContractEvent<RootRevokedEvent.InputTuple, RootRevokedEvent.OutputTuple, RootRevokedEvent.OutputObject>;

    filters: {
      
      'IssuerAuthorizationUpdated(address,bool)': TypedContractEvent<IssuerAuthorizationUpdatedEvent.InputTuple, IssuerAuthorizationUpdatedEvent.OutputTuple, IssuerAuthorizationUpdatedEvent.OutputObject>;
      IssuerAuthorizationUpdated: TypedContractEvent<IssuerAuthorizationUpdatedEvent.InputTuple, IssuerAuthorizationUpdatedEvent.OutputTuple, IssuerAuthorizationUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RootAnchored(bytes32,bytes32,address,string,uint256)': TypedContractEvent<RootAnchoredEvent.InputTuple, RootAnchoredEvent.OutputTuple, RootAnchoredEvent.OutputObject>;
      RootAnchored: TypedContractEvent<RootAnchoredEvent.InputTuple, RootAnchoredEvent.OutputTuple, RootAnchoredEvent.OutputObject>;
    

      'RootRevoked(bytes32,bytes32,address,address,uint256)': TypedContractEvent<RootRevokedEvent.InputTuple, RootRevokedEvent.OutputTuple, RootRevokedEvent.OutputObject>;
      RootRevoked: TypedContractEvent<RootRevokedEvent.InputTuple, RootRevokedEvent.OutputTuple, RootRevokedEvent.OutputObject>;
    
    };
  }