/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CredentialAnchor } from './CredentialAnchor.js';
export * as factories from './factories/index.js';
export { CredentialAnchor__factory } from './factories/CredentialAnchor__factory.js';