export function getElements() {
  return {
    walletWidget: document.querySelector("#wallet-widget"),
    walletWidgetHandle: document.querySelector("#wallet-widget-handle"),
    walletWidgetBody: document.querySelector("#wallet-widget-body"),
    walletWidgetToggle: document.querySelector("#toggle-wallet-widget"),
    connectWallet: document.querySelector("#connect-wallet"),
    refreshNetwork: document.querySelector("#refresh-network"),
    walletStatus: document.querySelector("#wallet-status"),
    walletStatusLabel: document.querySelector("#wallet-status-label"),
    networkValue: document.querySelector("#network-value"),
    accountValue: document.querySelector("#account-value"),
    copyAccount: document.querySelector("#copy-account"),
    contractAddress: document.querySelector("#contract-address"),
    copyContract: document.querySelector("#copy-contract"),
    connectionMessage: document.querySelector("#connection-message"),
    issuerViewButtons: Array.from(document.querySelectorAll("[data-issuer-view-button]")),
    issuerViews: Array.from(document.querySelectorAll("[data-issuer-view]")),
    buildMerkleTree: document.querySelector("#build-merkle-tree"),
    generateQr: document.querySelector("#generate-qr"),
    submitRoot: document.querySelector("#submit-root"),
    downloadQr: document.querySelector("#download-qr"),
    issuanceMessage: document.querySelector("#issuance-message"),
    qrCodeCanvas: document.querySelector("#qr-code-canvas"),
    qrPayloadOutput: document.querySelector("#qr-payload-output"),
    qrGenerationProgress: document.querySelector("#qr-generation-progress"),
    qrGenerationProgressBar: document.querySelector("#qr-generation-progress-bar"),
    qrGenerationProgressLabel: document.querySelector("#qr-generation-progress-label"),
    merkleLegend: document.querySelector("#merkle-legend"),
    merkleTreeShell: document.querySelector("#merkle-tree-shell"),
    merkleTreeLines: document.querySelector("#merkle-tree-lines"),
    merkleTreeStage: document.querySelector("#merkle-tree-stage"),
    merkleTreeText: document.querySelector("#merkle-tree-text"),
    merkleRootInput: document.querySelector("#merkle-root"),
    batchCredentialsDropzone: document.querySelector("#batch-credentials-dropzone"),
    batchCredentialsFileInput: document.querySelector("#batch-credentials-file"),
    batchCredentialsFileName: document.querySelector("#batch-credentials-file-name"),
    batchCredentialsSummary: document.querySelector("#batch-credentials-summary"),
    merkleBuildProgress: document.querySelector("#merkle-build-progress"),
    merkleBuildProgressBar: document.querySelector("#merkle-build-progress-bar"),
    merkleBuildProgressLabel: document.querySelector("#merkle-build-progress-label"),
    batchIdInput: document.querySelector("#batch-id"),
    issuedAtInput: document.querySelector("#issued-at"),
    proofTargetIndex: document.querySelector("#proof-target-index"),
    issuerProofInput: document.querySelector("#issuer-proof-input"),
    issuerForm: document.querySelector("#issuer-form"),
    recipientInput: document.querySelector("#recipient"),
    credentialIdInput: document.querySelector("#credential-id"),
    achievementCodeInput: document.querySelector("#achievement-code"),
    issueDateInput: document.querySelector("#issue-date"),
    issuerIdInput: document.querySelector("#issuer-id")
  };
}

export function getVerifierElements() {
  return {
    verificationMessage: document.querySelector("#verification-message"),
    verificationStatusCard: document.querySelector("#verification-status-card"),
    verificationStatusTitle: document.querySelector("#verification-status-title"),
    verificationStatusCopy: document.querySelector("#verification-status-copy"),
    verificationChipRow: document.querySelector("#verification-chip-row"),
    verificationOwnerDetails: document.querySelector("#verification-owner-details"),
    verificationBatchDetails: document.querySelector("#verification-batch-details"),
    verificationProofDetails: document.querySelector("#verification-proof-details")
  };
}
